version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1798
      POSTGRES_DB: app-db
    ports:
      - '5432:5432'
    networks:
      - app-network

  server:
    image: server:0.0.1
    links:
      - redis
      - postgres
    depends_on:
      - postgres
      - redis
    ports:
      - '8080:8080'
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    links:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - server
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email a.aldwaeb@gmail.com --agree-tos --no-eff-email --staging -d api.hamoood.codes

volumes:
  certbot-etc:
  certbot-var:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/react-node-playground/server/dhparam/
      o: bind
  web-root:
    driver: local

networks:
  app-network:
    driver: bridge
